### ISSUE TITLE
filtering with nested functions not working

### ISSUE THREAD

**Issue by dylanlingelbach** [Vicnovais/odata-sequelize#28]
Using a query string of: `?$filter=substringof('a',tolower(column))`

I get the following exception:
```
TypeError: Cannot read property 'name' of undefined
        at parseFunction (.../node_modules/odata-sequelize/index.js:141:83)
        at parseFunctionCall (.../node_modules/odata-sequelize/index.js:209:7)
        at preOrderTraversal (.../node_modules/odata-sequelize/index.js:222:5)
        at parseFilter (.../node_modules/odata-sequelize/index.js:335:16)
        at module.exports (.../node_modules/odata-sequelize/index.js:380:18)
```

It looks like the function parser doesn't support nested functions: https://github.com/Vicnovais/odata-sequelize/blob/996ab3b96a55423661f20b000d73e1fef2408629/index.js#L141

**Comment by Vicnovais** [comment]
Thanks for your report!
Fixed on 14824ab1889190f3061217cebab26e55f5acb65a, please update the package using NPM.
